import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "100", "400"],
  style: ["normal"],
});

export const metadata = {
  title: "My app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Navbar />
        <p>{metadata.description}</p>

        {children}
      </body>
    </html>
  );
}
